version: '3.7'
services:

  flyway:
    image: flyway/flyway:9.16
    # entrypoint: 
    #   - /bin/bash
    #   - -c
    #   - |
    #     ls -al /flyway/sql
    #     ls -al /flyway/conf
    command: 
      - info
      # - validate
      - migrate
      # - clean
      # - baseline
    networks:
      - mynetwork
    volumes:
      - $PROJECT_FULLPATH/sql:/flyway/sql
      - $PROJECT_FULLPATH/conf:/flyway/conf

networks:
  mynetwork:
    external: true